# version: '3.8'

# services:
#   redis:
#     container_name: redis
#     image: redis:6
#     command: redis-server /usr/local/etc/redis/redis.conf
#     ports:
#       - 6379:6379
#     volumes:
#       - ./config/redis.conf:/usr/local/etc/redis/redis.conf
#     networks:
#       - node_network
#   node:
#     build: .
#     container_name: express
#     ports:
#       - 8000:8000
#     environment:
#       - NAME=elshandi-septiawan
#       - PORT=8000
#       - REDIS_PORT=6379
#       - DATABASE_URL = mongodb://127.0.0.1:27017/elshandi-septiawan
#       - API_SECRET = "secret"
#     networks:
#       - node_network
#     volumes:
#       - .:/app
#   mongo:
#     container_name: mongo
#     image: mongo
#     volumes:
#     - ./data:/data/db
#     ports:
#     - '27017:27017'

# networks:
#   node_network:

version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - .docker/data/mongo:/data

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - .docker/data/redis:/data
    
  # Node api service
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # local->container
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_URL: mongodb://mongo_db:27017/elshandi-septiawan
    depends_on: 
      - mongo_db
      - redis

volumes:
  mongo_data: {}

networks:
  node_network: