version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - .docker/data/mongo:/data

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - .docker/data/redis:/data
    
  # Node api service
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # local->container
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_URL: mongodb://mongo_db:27017/elshandi-septiawan
      API_SECRET: "secret"
    depends_on: 
      - mongo_db
      - redis

volumes:
  mongo_data: {}

networks:
  node_network: